package cn.xdl.ydma.entity;

import java.io.Serializable;
import java.util.List;

public class Direction implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direction.id
     *
     * @mbg.generated Mon Sep 02 16:40:35 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direction.name
     *
     * @mbg.generated Mon Sep 02 16:40:35 CST 2019
     */
    private String name;
    
    //存储相关联的subject信息
    private List<Subject> subjects;
    
    //存储相关联的推荐course信息
    private List courses;

    public List getCourses() {
		return courses;
	}

	public void setCourses(List courses) {
		this.courses = courses;
	}

	public List<Subject> getSubjects() {
		return subjects;
	}

	public void setSubjects(List<Subject> subjects) {
		this.subjects = subjects;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column direction.id
     *
     * @return the value of direction.id
     *
     * @mbg.generated Mon Sep 02 16:40:35 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column direction.id
     *
     * @param id the value for direction.id
     *
     * @mbg.generated Mon Sep 02 16:40:35 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column direction.name
     *
     * @return the value of direction.name
     *
     * @mbg.generated Mon Sep 02 16:40:35 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column direction.name
     *
     * @param name the value for direction.name
     *
     * @mbg.generated Mon Sep 02 16:40:35 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}