package cn.xdl.ydma.dao;

import cn.xdl.ydma.entity.BrowsingHistory;
import org.apache.ibatis.jdbc.SQL;

public class BrowsingHistorySqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsing_history
     *
     * @mbg.generated Mon Sep 02 19:47:04 GMT+08:00 2019
     */
    public String insertSelective(BrowsingHistory record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("browsing_history");
        
        if (record.getUseId() != null) {
            sql.VALUES("use_id", "#{useId,jdbcType=INTEGER}");
        }
        
        if (record.getCourseId() != null) {
            sql.VALUES("course_id", "#{courseId,jdbcType=INTEGER}");
        }
        
        if (record.getBrowseTime() != null) {
            sql.VALUES("browse_time", "#{browseTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getVideoId() != null) {
            sql.VALUES("video_id", "#{videoId,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsing_history
     *
     * @mbg.generated Mon Sep 02 19:47:04 GMT+08:00 2019
     */
    public String updateByPrimaryKeySelective(BrowsingHistory record) {
        SQL sql = new SQL();
        sql.UPDATE("browsing_history");
        
        if (record.getUseId() != null) {
            sql.SET("use_id = #{useId,jdbcType=INTEGER}");
        }
        
        if (record.getCourseId() != null) {
            sql.SET("course_id = #{courseId,jdbcType=INTEGER}");
        }
        
        if (record.getBrowseTime() != null) {
            sql.SET("browse_time = #{browseTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getVideoId() != null) {
            sql.SET("video_id = #{videoId,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}